-- 0001_initial_schema.down.sql
DROP TABLE IF EXISTS reserva;
DROP TABLE IF EXISTS libro_autor;
DROP TABLE IF EXISTS multa;
DROP TABLE IF EXISTS prestamo;
DROP TABLE IF EXISTS usuariopassword;
DROP TABLE IF EXISTS socio;
DROP TABLE IF EXISTS autor;
DROP TABLE IF EXISTS libro;
DROP TABLE IF EXISTS editorial;